spring.application.name=api-paqteria
server.address=${API_DIRECCION:0.0.0.0}
server.port=${API_PUERTO:8443}
server.ssl.enabled=true
server.ssl.key-store=${API_TLS_KEYSTORE:file:./secrets/api-keystore.p12}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=${API_TLS_KEY_ALIAS:paqteria-api}
server.ssl.key-store-password=${API_TLS_KEYSTORE_PASSWORD}
server.ssl.enabled-protocols=TLSv1.3,TLSv1.2

spring.datasource.url=${PAQTERIA_DB_URL:jdbc:sqlserver://localhost:1433;databaseName=Paqteria;encrypt=true;trustServerCertificate=true;loginTimeout=30}
spring.datasource.username=${PAQTERIA_DB_USUARIO}
spring.datasource.password=${PAQTERIA_DB_CONTRASENA}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.maximum-pool-size=${PAQTERIA_DB_POOL:12}
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.sql.init.mode=never

paqteria.jwt.emisor=${PAQTERIA_JWT_EMISOR:https://api.paqteria.local}
paqteria.jwt.secreto-base64=${PAQTERIA_JWT_SECRETO_BASE64}
paqteria.jwt.minutos-vigencia=${PAQTERIA_JWT_MINUTOS:30}
paqteria.cors.origenes=${PAQTERIA_CORS_ORIGENES:http://localhost:5173,http://localhost:57290,http://localhost:8081,http://localhost:19006}
paqteria.inicial.admin-correo=${PAQTERIA_ADMIN_CORREO:}
paqteria.inicial.admin-nombre=${PAQTERIA_ADMIN_NOMBRE:Administrador PAQTERIA}
paqteria.inicial.admin-contrasena=${PAQTERIA_ADMIN_CONTRASENA:}

spring.jackson.default-property-inclusion=non_null
logging.level.mx.paqteria=INFO
